### ISSUE TITLE
Unable to fetch breeds data from Pet api

### ISSUE THREAD

**Issue by divakar54** [btholt/complete-intro-to-react-v6#35]
I am unable to fetch breeds data from the Pets api.
const res = await fetch(
        `http://pets-v2.dev-apis.com/breeds?animal=${animal}`
      );
the above line returns, 
{ "animal": "${animal}" }

**Comment by veeraraghavan** [comment]
@divakar54 I think the issue is because the request being fired is 
http://pets-v2.dev-apis.com/breeds?animal=${animal} as opposed to 
http://pets-v2.dev-apis.com/breeds?animal=dog 
This is because the template string has not been replaced ${animal} . Are you using the template literal **`**  

``
const res = await fetch(`http://pets-v2.dev-apis.com/breeds?animal=${animal}`);  
``

**Comment by divakar54** [comment]
I am using the template literal, but the problem got solved anyway. I was doing a small mistake somewhere else, the url works fine.
